feed/urls.py
from django.conf.urls import url

from . import views
from feed.models import Feed_Entry
from django.views.generic import ListView, DetailView


urlpatterns = [
    url(r'^$', views.feed, name='feed'),
    url(r'^group/(?P<group_id>[0-9]+)/$$', views.filterByGroup, name='filterByGroup'),
]

sapphire/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from . import views

from accounts.forms import LoginForm

urlpatterns = [
    url(r'^bs/$', auth_views.login, {'template_name': 'bs-4-header.html'}, name='bs-4'), #, 'authentication_form': LoginForm
    url(r'^admin/', admin.site.urls),
    url(r'^feed/', include('feed.urls')),
    url(r'^info/', include('info.urls')),
    url(r'^groups/', include('groups.urls')),
    url(r'^sheets/', include('sheets.urls')),
    url(r'^volunteer/', include('volunteer.urls')),
    url(r'^organizer/', include('organizer.urls')),
    url(r'^$', views.home, name='home'),
    url(r'^home/', include('volunteer.urls')),           #TODO this should be set programatically depending on auth type
    url(r'^login/$', auth_views.login, {'template_name': 'accounts/login.html'}, name='login'), #, 'authentication_form': LoginForm
    url(r'^logout/$', auth_views.logout, {'next_page' : '/accounts/logout_lander'}, name='logout'),    # Will redirect to the next page
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    # url(r'^', auth_views.login, {'template_name' : 'auth/login.html'}, name='login'),   #TODO this should remember you are logged in
    #url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

volunteer/urls.py
from django.conf.urls import url

from . import views
from utility.models import Event, Slot
from django.views.generic import ListView, DetailView


urlpatterns = [
    url(r'^calendar/', views.calendar, name='calendar'),
    url(r'^events/', views.events, name='events'),
    url(r'^event/(?P<event_id>[0-9]+)$', views.event, name='eventView'),
    url(r'^slot/(?P<slot_id>[0-9]+)$', views.slot, name='slotView'),
    url(r'^slots/', views.slots, name='slots'),
    url(r'^$', views.index, name='index'),      #NOTE This must be last otherwise it will always take precedent
    url(r'^slot/(?P<slot_id>[0-9]+)/volunteer/$', views.volunteer, name='volunteer'), #We should make this start with eventView instead of just having numbers
    url(r'^slot/(?P<slot_id>[0-9]+)/volunteer/(?P<user_id>[0-9]+)/$', views.volunteerForUser, name='volunteerForUser'), #We should make this start with eventView instead of just having numbers
    url(r'^accept/(?P<slot_id>[0-9]+)/$', views.accept, name='volunteerForUser'),
    url(r'^slot/(?P<slot_id>[0-9]+)/unvolunteer/$', views.unvolunteer, name='unvolunteer'), #We should make this start with eventView instead of just having numbers
    url(r'^signin/(?P<user_slot_id>[0-9]+)$', views.signin, name='signin'), #We should make this start with eventView instead of just having numbers
    url(r'^signout/(?P<user_slot_id>[0-9]+)$', views.signout, name='signout'), #We should make this start with eventView instead of just having numbers


    #url(r'^slot/(?P<slot_id>[0-9]+)/$', views.volunteer, name='volunteer'),

]

utility/models.py
from django.db import models
from django.db.models import Q
from datetime import datetime, timedelta, timezone

from django.contrib.auth.models import User, UserManager
from accounts.models import Profile
from groups.models import Group
import ast
from collections import OrderedDict
import json
import pytz

"""
Notes:
I have used models.CASCADE in all the db relationship on_delete cases. I do not
know if this is good practice or will result in errors later down the line.
"""

"""
A slot object allows volunteers to sign up for it and has a start time and end
time. It has a parent Event.
"""


class Slot(models.Model):
    def __str__(self):
        return 'Slot: ' + self.title
    objects = models.Manager()
    # TODO make sure this can only point to one Event and not more than that
    parentEvent = models.ForeignKey(
        'Event',
        on_delete=models.CASCADE,
        null=True
    )
    parentGroup = models.ForeignKey(
        Group,
        on_delete=models.CASCADE,
        null=True
    )
    start = models.DateTimeField()
    end = models.DateTimeField()

    # The minimun number of volunteers this slot needs to have. Set by Event
    # organizer and factored into slot priority
    minVolunteers = models.IntegerField(blank=True, null=True)
    # The maximum number of volunteers this slot can have. Set by Event
    # organizer and stops too many Profiles from signing up
    maxVolunteers = models.IntegerField(blank=True, null=True)
    # TODO allow a getPriority() function to get the instantanious priority of
    # the Event object

    title = models.CharField(max_length=240)
    # The String descriptionof the event
    description = models.CharField(max_length=960, blank=True, null=True)

    # The String location Name of the Event
    location = models.CharField(max_length=240, blank=True, null=True)
    # The String address of the Event
    address = models.CharField(max_length=240, blank=True, null=True)
    # The String city of the Event'
    city = models.CharField(max_length=240, blank=True, null=True)
    # The String state of event
    # TODO: This should be restored to 2 if that was not an accident
    state = models.CharField(max_length=200, blank=True, null=True)
    # The Integer zip code of the Event
    zip_code = models.IntegerField(blank=True, null=True)

    paymentPerHour = models.DecimalField(blank=True, null=True, default=0, max_digits=5, decimal_places=2)

    extraFields = models.CharField(max_length=255, blank=True, null=True)

    private = models.BooleanField(blank=False, null=False, default=False)

    def is_payment_nonzero(self):
        return self.paymentPerHour != 0

    def is_volunteered(self, user):
        return User_Slot.objects.filter(parentSlot=self, volunteer=user).first() != None


    def getNumberUserSlotsTotal(self):
        return len(User_Slot.objects.filter(parentSlot=self))

    def getNumberUserSlotsFilled(self):
        return len(User_Slot.objects.filter(parentSlot=self).exclude(volunteer=None))

    def get_users_groups_slots(user):
        groups = Group.get_is_member_list(user)
        events = None
        slots = None
        for group in groups:
            if (events == None):
                events = Event.objects.filter(parentGroup=group)
            else:
                groups_events = Event.objects.filter(parentGroup=group)
                events = events | groups_events

            if (slots == None):
                slots = Slot.objects.filter(parentGroup=group)
            else:
                groups_slots = Slot.objects.filter(parentGroup=group)
                slots = slots | groups_slots

        if events == None:
            return None

        for event in events:
            if (slots == None):
                slots = Slot.objects.filter(parentEvent=event)
            else:
                events_slots = Slot.objects.filter(parentEvent=event)
                slots = slots | events_slots


        if (slots == None):
            return slots
        return slots.order_by(
            'start')  # Slot.objects.filter(Q(parentEvent.parentGroup.get_is_member(user))).objects.order_by('start')

    def get_extra(self):
        if (self.extraFields != None):
            return self.extraFields.split(',')


    def get_group(self):
        if self.parentEvent is not None:
            group = self.parentEvent.parentGroup
        else:
            group = self.parentGroup

        return group


class User_Slot(models.Model):
    def __str__(self):
        return 'User_Slot: ' + self.parentSlot.title
    volunteer = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )

    parentSlot = models.ForeignKey(
        Slot,
        on_delete=models.CASCADE,
        null=False,
    )

    signin = models.DateTimeField(blank=True, null=True)
    signout = models.DateTimeField(blank=True, null=True)

    def is_signin_null(self):
        return self.signin == None

    def is_signout_null(self):
        return self.signout == None

    def is_volunteer_null(self):
        return self.volunteer == None

    difference = models.CharField(blank=True, max_length=100, null=True)

    payment = models.DecimalField(blank=True, null=False, default=0, max_digits=10, decimal_places=2)

    extraFields = models.CharField(blank=True, max_length=240, null=True)

    def getExtraFieldValues(self):
        efs = json.loads(self.extraFields)
        return [val for key,val in efs.items()]


    accepted = models.CharField(blank=True, max_length=240, default="No")

    value = None  # this is used to export the extra fields to html


    def updateDeltaTimes(self):
        if (self.signin != None and self.signout != None):
            signout, signin = self.signout, self.signin
            print(signout, signin)
            # import pdb; pdb.set_trace() 

            deltaTime = signout - signin
            seconds = deltaTime.seconds

            
            self.difference = str(timedelta(seconds=seconds))
            self.payment = (seconds/60/60) * (float(self.parentSlot.paymentPerHour))

            self.save()

    def getUserSlots(group):
        events = Event.objects.filter(parentGroup=group)
        slots = Slot.objects.filter(parentGroup=group)

        for event in events:
            if (slots == None):
                slots = Slot.objects.filter(parentEvent=event)

            else:
                slots = slots | Slot.objects.filter(parentEvent=event)

        user_slots = None

        for slot in slots:
            if (user_slots == None):
                user_slots = User_Slot.objects.filter(parentSlot=slot)

            else:
                user_slots = user_slots | User_Slot.objects.filter(parentSlot=slot)

        return user_slots

    def get_extra(self):
        ans = json.loads(self.extraFields.replace('\'', '\"'), object_pairs_hook=OrderedDict)
        if type(ans) is type([]):
            return {}
        return ans

    def save_extra(self, newList):
        self.extraFields = json.dumps(newList)

    def set_extra(self, field, newVal):
        a = self.get_extra()
        a[field] = newVal
        self.save_extra(a)

    def remove_extra(self, field):
        self.extraFields = self.get_extra()
        del self.extraFields[field]

    def prep_html(self):
        print(self.get_extra(), type(self.get_extra()))
        self.value = list(self.get_extra().items())


class Event(models.Model):
    def __str__(self):
        return 'Event: ' + self.name
    parentGroup = models.ForeignKey(
        Group,
        on_delete=models.CASCADE,
        null=False,
    )
    is_single = models.BooleanField(default=False)
    # type = models.CharField(max_length=80)
    objects = models.Manager()
    # The organizer of the Event
    organizer = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=False
    )
    # The string name of the Event
    name = models.CharField(max_length=80)
    # The String descriptionof the event
    description = models.CharField(blank=True, max_length=960)

    # The String location Name of the Event
    location = models.CharField(blank=True, max_length=240)
    # The String address of the Event
    address = models.CharField(blank=True, max_length=240)
    # The String city of the Event'
    city = models.CharField(blank=True, max_length=240)
    # The String state of event
    state = models.CharField(blank=True, max_length=200)
    # type = models.CharField(max_length=30)
    # The Integer zip code of the Event
    zip_code = models.IntegerField(blank=True, null=True)

    slots = models.ForeignKey(
        Slot,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="slot_set"
    )
    start = models.DateTimeField(blank=True, null=True)
    end = models.DateTimeField(blank=True, null=True)

    private = models.BooleanField(blank=False, null=False, default=False)

    # The minimun number of volunteers this slot needs to have. Set by Event
    # organizer and factored into slot priority
    # minVolunteers = models.IntegerField(null=True)
    # The maximum number of volunteers this slot can have. Set by Event
    # organizer and stops too many Profiles from signing up
    # maxVolunteers = models.IntegerField(null=True)
    # TODO allow a getPriority() function to get the instantanious priority of
    # the Event object
    # in_person = models.NullBooleanField(null=True)
    # A one to many relationship holding the Slots for an Event object

    # RAISING ERRORS

    # slots = models.ForeignKey(
    #     'Slot',
    #     on_delete=models.CASCADE,
    #     null=True,
    #     blank=True
    # )
    def get_in_person(self):
        if self.in_person:
            return 'Yes'
        return 'No'

    def get_users_groups_events(user):
        groups = Group.get_is_member_list(user)
        events = None
        for group in groups:
            if (events == None):

volunteer/models.py
from django.db import models

# Create your models here.

volunteer/forms.py
from datetime import datetime, timezone
from django import forms
from utility.models import Slot, Event

from .helpers import get_dt

class FilterTimeForm(forms.Form):
    starttime = forms.DateTimeField(label='Start', input_formats=['%Y-%m-%d'],
    widget=forms.DateTimeInput(
        attrs={'type': 'date',
               'class': 'form-control',
               'value': get_dt().strftime("%Y-%m-%d")}))

    endtime = forms.DateTimeField(label='End', input_formats=['%Y-%m-%d'],
    widget=forms.DateTimeInput(
        attrs={'type': 'date',
               'class': 'form-control',
               'value': get_dt().strftime("%Y-%m-%d")}))

    def __init__(self, *args, **kwargs):
        super(FilterTimeForm, self).__init__(*args, **kwargs)


    def getStart(self):
        return self.cleaned_data['starttime']

    def getEnd(self):
        return self.cleaned_data['endtime']


class SearchForm(forms.Form):
    query = forms.CharField(label='', required=False, max_length=120, widget=forms.TextInput(
        attrs={'type': 'text',
               'class': 'form-control',
               'placeholder': 'Search'}))

    def clean_query(self):
        return self.cleaned_data['query']

    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        query = self.cleaned_data['query']
        return query

resources/templates/volunteer/calendar.html
{% extends "header.html" %}

{% block content %}
  <h1>Calendar</h1>

  <table class="table table-hover">
  <thead>
    <tr>
      <th>Event</th>
      <th>Slot</th>
      <th>Location</th>
      <th>Name</th>
      <th>Start</th>
      <th>End</th>
    </tr>
  </thead>
  <tbody>
    
  </tbody>
  </table>

{% endblock %}

resources/templates/volunteer/event.html
{% extends "header.html" %}
{% load permission_tags %}
{% load tz %}

{% block content %}

	<p class="text-right">
		<a href="/groups/{{ event.parentGroup.id }}">{{ event.parentGroup.name }}</a>
	</p>

	<div class="jumbotron">

		<h1 class="display-1">{{ event.name }}</h1>
		<a class="lead" href="http://www.google.com/calendar/event?
				action=TEMPLATE
				&text={{ event.name }}
				&dates={{ event.start|utc|date:"Ymd\\THi00\\Z" }}/{{ event.end|utc|date:"Ymd\\THi00\\Z" }}
				&details={{ event.description }}
				&location={{ event.location }}
				&trp=true
				&sprop=website:{{ request.build_absolute_uri }}"
				target="_blank" rel="nofollow" data-toggle="tooltip" data-placement="bottom" title="Open in Google Calendar">
			{{ event.start }} - {{ event.end }}
		</a>

		<div id="accordion" role="tablist">
			<div class="card">
				<div class="card-header" role="tab" id="headingOne" data-toggle="tooltip" data-placement="bottom" title="Open map view">
					<h5 class="mb-0">
						<a data-toggle="collapse" href="#collapseOne" role="button" aria-expanded="true"
						   aria-controls="collapseOne">
							{{ event.location }}: {{ event.address }} {{ event.city }}, {{ event.state }} {{ event.zip_code }}
						</a>
					</h5>
				</div>

				<div id="collapseOne" class="collapse toggle" role="tabpanel" aria-labelledby="headingOne"
				     data-parent="#accordion">

					<div class="embed-responsive embed-responsive-16by9">
						<iframe class="embed-responsive-item"
						        src="https://www.google.com/maps/embed/v1/search?q={{ event.address }} {{ event.city }}, {{ event.state }} {{ event.zip_code }}&key=AIzaSyB-YQD-s4ery8KQRnzX7FhZsBC4SeFRcjA"
						        allowfullscreen></iframe>
					</div>

					<p class="text-danger">Map will only function correctly if a valid address has been entered</p>
				</div>
			</div>

			<h1></h1>
			<p class="text-left">{{ event.description }}</p>
		</div>

		{% if is_organizer %}
			<div class="row">
				<a class="col-sm-4 nodec" href="/organizer/updateEvent/{{ event.id }}" data-toggle="tooltip" data-placement="bottom" title="Edit {{ profile.eventName }} fields">
					<button class="btn btn-primary btn-block">
						<i class="fas fa-edit"></i> Edit
					</button>
				</a>
				<a class="col-sm-2 nodec" href="/sheets/fromEvent/{{ event.id }}" data-toggle="tooltip" data-placement="top" title="Download {{ profile.eventName }} data">
					<button class="btn btn-block btn-success">
						<i class="fas fa-table"></i> Spreadsheet
					</button>
				</a>
				<a class="col-sm-2 nodec" href="/organizer/sendMail/event/{{ event.id }}" data-toggle="tooltip" data-placement="bottom" title="Email users about {{ profile.eventName }}">
					<button class="btn btn-block btn-success"><i class="fas fa-envelope"></i> Email</button>
				</a>

				<a class="col-sm-2 nodec" href="/organizer/event/{{ event.id }}/console" data-toggle="tooltip" data-placement="bottom" title="Open {{ profile.eventName }} organizer console">
					<button class="btn btn-primary btn-block">
						<i class="fas fa-terminal"></i> Console
					</button>
				</a>


				<div class="btn-group col-sm-2 nodec">
					<button class="btn btn-danger btn-block dropdown-toggle"
						style="padding-bottom: 14px; padding-top: 6px;" data-toggle="dropdown" aria-haspopup="true"
						aria-expanded="false">
						<span  data-toggle="tooltip" data-placement="bottom" title="Delete event"> 
							<i class="fas fa-trash-alt"></i> 
							<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
						</span>
					</button>
					<div class="dropdown-menu px-2">
						<h1 class="dropdown-header">Are you sure?</h1>
						<a class="nodec"
						   href="{% url 'deleteEvent' event_id=event.id %}?next={{ '/home/feed/'|urlencode }}">
							<button class="btn btn-danger btn-block">Yes</button>
						</a>
					</div>
				</div>
			</div>
		{% endif %}
	</div>




	<h3>{{ profile.slotName }}s
		{% if is_organizer %}
			<a class="plus" href="{% url 'addSlot' event_id=event.id %}" data-toggle="tooltip" data-placement="bottom" title="Add {{ profile.slotName }} to this event">
				+
			</a>
		{% endif %}
	</h3>

    <table id="datatable" class="table table-hover">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Start</th>
                    <th>End</th>
                    <th>Workers</th>
                    <th>{{ profile.slotName }}s Taken</th>
                    {% if is_organizer %}
                        <th>Delete</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for slot in event.slot_set.all|dictsort:"start" %}
            <tr>
                <td><a href="/volunteer/slot/{{ slot.id }}">{{ slot.title }}</a></td>
                <td>{{ slot.start }}</td>
                <td>{{ slot.end }}</td>
                <td>
                    <a href="#" data-toggle="popover" data-trigger="hover" title="Volunteers" id="volunteer-popover-{{ slot.id }}">
                        <i class="fas fa-user-circle"></i>
                    </a>
                </td>
                <td>
                    {% ifnotequal slot.maxVolunteers 0 %}
                        {{ slot.user_slot_set.all|volunteer_count }}/{{ slot.user_slot_set.all|length }}
                    {% endifnotequal %}

                    {% ifequal slot.maxVolunteers 0 %}
                        <a title="This {{ profile.slotName }} is unlimited" style="border-bottom: 1px dotted blue;">∞</a>
                    {% endifequal %}
                </td>
                {% if is_organizer %}
                    <td>
                        <div class="btn-group">
                            <button class="btn btn-danger dropdown-toggle" data-toggle="dropdown"
									aria-haspopup="true" aria-expanded="false">
								<span  data-toggle="tooltip" data-placement="bottom" title="Remove {{ profile.slotName }}">
									<i class="fas fa-trash-alt"></i>
								</span>
                            </button>
                            <div class="dropdown-menu px-2">
                                <h1 class="dropdown-header">Are you sure?</h1>
                                <a class="nodec"
                                   href="{% url 'deleteSlot' slot_id=slot.id %}?next={{ request.path|urlencode }}">
                                    <button class="btn btn-danger btn-block">Yes</button>
                                </a>
                            </div>
                        </div>
                    </td>
                {% endif %}

            </tr>
        {% endfor %}
            </tbody>
        </table>

	{% if is_organizer or not event.private %}
		{% for slot in event.slot_set.all|dictsort:"start" %}
				<div id="volunteer-popover-{{ slot.id }}-content" class="d-none">
					{% for user_slot in slot.user_slot_set.all %}
						<button class="btn btn-sm btn-default">
							{{ user_slot.volunteer.username }}
						</button>
					{% empty %}
						No Volunteers
					{% endfor %}
				</div>
		{% endfor %}
	{% else %}
		{% for slot in event.slot_set.all|dictsort:"start" %}
			<div id="volunteer-popover-{{ slot.id }}-content" class="d-none">
				{% for user_slot in slot.user_slot_set.all %}
					{% if user_slot.volunteer == volunteer %}
						<button class="btn btn-sm btn-default">
							{{ user_slot.volunteer.username }}
						</button>
					{% endif %}
				{% empty %}
					No Volunteers
				{% endfor %}
			</div>
		{% endfor %}
	{% endif %}
	<script>
		$(document).ready(function(){
		    $("[data-toggle=popover]").each(function(i, obj) {
				$(this).popover({
					html: true,
					content: function() {
					var id = $(this).attr('id');
					return $('#'+id+'-content').html();
					}
				});
			});
		});
	</script>
{% endblock %}

resources/templates/volunteer/events.html
{% extends "header.html" %}
{% load permission_tags %}
{% load tz %}

{% block content %}

	<h1 class="display-1 text-center">{{ profile.eventName }}s
        <a class="plus" href="/organizer/addEvent/" data-toggle="tooltip" data-placement="bottom" title="Create {{ profile.eventName }}">+</a>
    </h1>
	{% include 'volunteer/filter_fragment.html' %}
	{% include 'volunteer/filter_display_fragment.html' %}

    {% if events.count == 0 %}
        <h3 class="display-3">No {{ profile.eventName }}s found with these filters.</h3>
    {% else %}

        <table id="datatable" class="table table-hover">
            <thead>
                <tr>
                    <th>{{ profile.eventName }}</th>
                    <th>Group</th>
                    <th>Location</th>
                    <th>Time</th>
                </tr>
            </thead>
            <tbody>
                {% for event in events %}
                    <tr>
                        <td><a href="/volunteer/event/{{ event.id }}">{{ event.name }}</a></td>
                        <td><a href="/groups/{{ event.parentGroup.id }}">{{ event.parentGroup.name }}</a></td>
                         <td><a href="http://maps.google.com/?q={{ event.location }}"
                                   target="_blank" data-toggle="tooltip" data-placement="bottom" title="Open in Google Maps">
                                   {{ eventevent.location }}</a></td>
                        <td>
                                <a href="http://www.google.com/calendar/event?action=TEMPLATE&text={{ event.name }}&dates={{ event.start|utc|date:"Ymd\\THi00\\Z" }}/{{ event.end|utc|date:"Ymd\\THi00\\Z" }}&details={{ event.description }}&location={{ event.location }}&trp=true&sprop=website:{{ request.build_absolute_uri }}"
                                        target="_blank" rel="nofollow"
                                        data-toggle="tooltip" data-placement="bottom" title="Open in Google Calendar">
                                    {{ event.start }} - {{ event.end }}
                                </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
		



{% endblock %}

resources/templates/volunteer/filter_display_fragment.html
<div class="mt-2 text-left">
	{% if groupfilter or daterangefilter or voluntoldfilter %}
		{% load name_from_id %}
		<p class="small">
			<i class="fas fa-filter mr-2"></i>
			{% if groupfilter %}
				<button class="btn btn-sm mb-1">
					Groups: {{ groupfilter|group_name_from_id }}
					<a href="?groupfilter=&distancefilter={{ distancefilter }}&daterangefilter={{ daterangefilter }}&voluntold={{ voluntold }}">
						<i class="fas fa-times-circle" style="color: red;"></i>
					</a>
				</button>
			{% endif %}
			{% if distancefilter %}
				<button class="btn btn-sm mb-1">
					Distance: {{ distancefilter }} miles
					<a href="?groupfilter={{ groupfilter }}&distancefilter=&daterangefilter={{ daterangefilter }}&voluntold={{ voluntold }}">
						<i class="fas fa-times-circle" style="color: red;"></i>
					</a>
				</button>
			{% endif %}
			{% if daterangefilter %}
				<button class="btn btn-sm mb-1">
					Date range: {{ daterangefilter|format_daterange }}
					<a href="?groupfilter={{ groupfilter }}&distancefilter={{ distancefilter }}&daterangefilter=&voluntold={{ voluntold }}">
						<i class="fas fa-times-circle" style="color: red;"></i>
					</a>
				</button>
			{% endif %}
			{% if voluntoldfilter == "true" %}
				<button class="btn btn-sm mb-1">
					Voluntold only
					<a href="?groupfilter={{ groupfilter }}&distancefilter={{ distancefilter }}&daterangefilter={{ datefilter }}&voluntold=">
						<i class="fas fa-times-circle" style="color: red;"></i>
					</a>
				</button>
			{% endif %}

			<a class="btn btn-danger btn-sm mb-1" href="?groupfilter=&distancefilter=&daterangefilter=&voluntold=">
				Clear all
			</a>
		</p>
	{% else %}
		<p class="small">
			<i class="fas fa-filter mr-2"></i>
			<button class="btn btn-sm" aria-pressed="true" data-toggle="collapse" href="#filterPanel" role="button" id="filterPanelToggle">
				No filters
			</button>
		</p>
	{% endif %}
</div>

resources/templates/volunteer/slots.html
{% extends "header.html" %}
{% load tz %}

{% block content %}
	<h1 class="display-1">{{ profile.slotName }}s
        <a class="plus" href="/organizer/addSingleSlot/" data-toggle="tooltip" data-placement="bottom" title="Add slot">+</a>
    </h1>
	{% include 'volunteer/filter_fragment.html' %}
	{% include 'volunteer/filter_display_fragment.html' %}
	
    {% if slots.count == 0 %}
        <h3 class="display-3">No {{ profile.slotName }}s found with these filters.</h3>
    {% else %}
        <table id="datatable" class="table table-hover">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>{{ profile.eventName }}</th>
                    <th>Time</th>
                </tr>
            </thead>
            <tbody>
            {% for slot in slots %}
                <tr>
                    <td><a href="/volunteer/slot/{{ slot.id }}" >{{ slot.title }}</a></td>
                    <td>
                        {% if not slot.parentEvent %}
                            <span data-toggle="tooltip" data-placement="bottom" title="No parent event">None</span>
                        {% else %}
                            <a href="/volunteer/event/{{ slot.parentEvent.id }}">
                                {{ slot.parentEvent.name }}
                            </a>
                        {% endif %}
                    </td>
                    <td>
                        <a href="http://www.google.com/calendar/event?action=TEMPLATE&text={{ slot.title }}&dates={{ slot.start|utc|date:"Ymd\\THi00\\Z" }}/{{ slot.end|utc|date:"Ymd\\THi00\\Z" }}&details={{ slot.description }}&location={{ slot.location }}&trp=true&sprop=website:{{ request.build_absolute_uri }}"
							target="_blank" rel="nofollow"
							data-toggle="tooltip" data-placement="bottom" title="Open in Google Calendar">
                            {{ slot.start }} - {{ slot.end }}
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
		

{% endblock %}